encoder_layers: 18
pretrained: True
num_scales: 4
learning_rate: 0.0001
scheduler_step_size: 30
weight_decay: 0.1
width: 1280
height: 384
min_depth: 0.1
max_depth: 100
num_epochs: 50
batch_size: 1
tensorboard_step: 3
num_workers: 0
use_stereo: False
train_config_path: configs/datasets/basic_train_dataset.yml
valid_config_path: configs/datasets/basic_validation_dataset.yml
test_config_path: configs/datasets/basic_test_dataset.yml
log_dir: experiments/basic_model
gt_path: data/gt_example
metrics: True
use_fpn: False
