encoder_layers: 18
pretrained: True
num_scales: 4
learning_rate: 0.00002
scheduler_step_size: 10
weight_decay: 0.1
width: 1280
height: 384
num_epochs: 15
batch_size: 8
tensorboard_step: 1000
num_workers: 12
use_stereo: False
train_config_path: configs/full_train_dataset.yml
valid_config_path: configs/full_validation_dataset.yml
test_config_path: configs/full_test_dataset.yml
log_path: models/8_26_eigen_zhou