resnet_layers: 18
pretrained: True
num_scales: 4
learning_rate: 0.0001
scheduler_step_size: 15
weight_decay: 0.1
width: 1024
height: 320
min_depth: 0.1
max_depth: 100
num_epochs: 20
batch_size: 10
tensorboard_step: 1000
num_workers: 12
use_stereo: False
train_config_path: configs/datasets/eigen_zhou_train_two_frames_dataset.yml
valid_config_path: configs/datasets/eigen_zhou_validation_two_frames_dataset.yml
lidar_test_config_path: configs/datasets/eigen_test_dataset.yml
gt_depthmap_test_config_path: configs/datasets/eigen_benchmark_test_dataset.yml
qual_config_path: configs/datasets/qualitative_dataset.yml
log_dir: experiments/two_frames_m
gt_path: data/kitti_gt
metrics: True
