encoder_layers: 18
pretrained: True
num_scales: 1
learning_rate: 0.0001
scheduler_step_size: 30
weight_decay: 0.1
width: 1280
height: 384
num_epochs: 50
batch_size: 2
tensorboard_step: 3
num_workers: 0
train_config_path: configs/basic_train_dataset.yml
valid_config_path: configs/basic_validation_dataset.yml