num_epochs: 50
learning_rate: 0.0001
scheduler_step_size: 20
weight_decay: 0.1
batch_size: 1
num_workers: 0
use_monocular: False
use_stereo: True
min_depth: 0.1
max_depth: 100
num_scales: 4  
tensorboard_step: 1
metrics: True
log_dir: experiments/basic_s
gt_dir: data/gt_example

depth_network:
  layers: 18
  densenet: False
  fpn: False
  pretrained: True

pose_network:
  layers: 18
  densenet: False
  pretrained: True

image:
  width: 1024
  height: 320
  crop: False
  color: RGB

dataset_config_paths:
  train: configs/datasets/basic_train_dataset.yml
  val: configs/datasets/basic_validation_dataset.yml
  test_lidar: configs/datasets/basic_test_dataset.yml
  test_gt_map: configs/datasets/basic_test_dataset.yml 
  qual: configs/datasets/basic_qualitative_dataset.yml
