encoder_layers: 18
pretrained: True
num_scales: 1
learning_rate: 0.0001
scheduler_step_size: 15
weight_decay: 0.1
width: 1280
height: 384
num_epochs: 20
batch_size: 8
tensorboard_step: 1000
num_workers: 12
use_stereo: True
train_config_path: configs/full_train_dataset.yml
valid_config_path: configs/full_validation_dataset.yml