train_config_path: configs/scene_test.yml
encoder_layers: 18
pretrained: True
num_scales: 1
learning_rate: 0.0001
scheduler_step_size: 15
weight_decay: 0.1
width: 1280
height: 384
num_epochs: 200
batch_size: 6
display_predictions: True